use_frameworks!

platform :ios, '8.0'

target 'WGStringTool_Example' do
  pod 'WGStringTool', :path => '../'

  target 'WGStringTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
